### ISSUE TITLE
.DS_storeに関して

### ISSUE THREAD

**Issue by su-san1129** [webcamp-sabae/metal-EC#16]
devから分岐させたadminファイルに、作成したcds_createをマージしようとしたところ、
DS_storeがコンフリクトしました。現在、Pull requestsしているものです。
gitignoreに記述を追加して対応しましたが、コンフリクトは直らず......

原因解明につとめますが、明日以降は、作業が出来ない時間が多いためこちらに記述しました。

**Comment by osuke-noguchi** [comment]
了解です！
